contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hic channel"
    url: https://nfcore.slack.com/channels/hic
    about: Discussion about the nf-core/hic pipeline
